#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'coloredlogs==15.0','console_scripts','coloredlogs'
__requires__ = 'coloredlogs==15.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('coloredlogs==15.0', 'console_scripts', 'coloredlogs')()
    )
