#!/bin/bash
source /usr/local/bin/config.ini

# source /usr/local/bin/configS.ini
datosDescarga=".datosdescarga.log"
# extract the protocol
proto="$(echo $1 | grep :// | sed -e's,^\(.*://\).*,\1,g')"
# remove the protocol
url="$(echo ${1/$proto/})"
# extract the user (if any)
user="$(echo $url | grep @ | cut -d@ -f1)"
# extract the host and port
hostport="$(echo ${url/$user@/} | cut -d/ -f1)"
# by request host without port    
host="$(echo $hostport | sed -e 's,:.*,,g')"
# by request - try to extract the port
port="$(echo $hostport | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
# extract the path (if any)
path="$(echo $url | grep / | cut -d/ -f2-)"

msg()
{
    BRAN='\033[1;37m' && VERMELHO='\e[31m' && VERDE='\e[32m' && AMARELO='\e[33m'
    AZUL='\e[34m' && MAGENTA='\e[35m' && MAG='\033[1;36m' && NEGRITO='\e[1m' && SEMCOR='\e[0m'
    case $1 in
    -ne) cor="${VERMELHO}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
    -pur) cor="${MAGENTA}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -ama) cor="${AMARELO}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -verm) cor="${AMARELO}${NEGRITO}[!] ${VERMELHO}" && echo -e "${cor}${2}${SEMCOR}";;
    -azu) cor="${MAG}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -verd) cor="${VERDE}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -red) cor="${VERMELHO}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
    -bla) cor="${BRAN}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
    -bar2) cor="${AZUL}${NEGRITO}======================================================" && echo -e "${cor}${SEMCOR}";;
    -bar) cor="${AZUL}${NEGRITO}========================================" && echo -e "${cor}${SEMCOR}";;
    esac
}

viki_download ()
{
    local url_viki="$1"
    # https://www.viki.com/videos/1172625v-true-beauty-episode-1
    # --write-sub --sub-lang es
    # youtube-dl --add-header "x-viki-app-ver: 2.2.5.1428709186" --add-header "x-viki-as-id: 100005a" --write-sub --sub-lang es --sub-format srt --username "$VIKI_USER" --password "$VIKI_PASS" "$url_viki"
    # ls -alh
    # msg -azu "listooooo" 
    # read


    # youtube-dl --write-sub --sub-lang es --sub-format srt --username "$VIKI_USER" --password "$VIKI_PASS" "$url_viki"
    # youtube-dl --write-sub --sub-lang es --sub-format srt --username "47755b56c8@firemailbox.club" --password "9999zzzz" "$url_viki"
    youtube-dl --write-sub --sub-lang es --sub-format srt --skip-download --username "47755b56c8@firemailbox.club" --password "9999zzzz" "$url_viki"
    # my_mpd=$(ls *.mpd)
    manifest_data=$(youtube-dl  "$url_viki" -J)
    manifest=$(echo "$manifest_data" | jq -r '.requested_formats | .[].manifest_url')
    manifest_title=$(echo "$manifest_data" | jq -r '.title')
    wget $manifest -O "manifest.mpd"
    my_mpd="manifest.mpd"
    url_mpd=$(cat "$my_mpd" | grep -i 'mpd</BaseURL>' | awk -F '>' '{print $2}' | cut -d"<" -f1)
    [[ -n "${url_mpd}" ]] && rm "manifest.mpd"

    if [[ ! $url_mpd ]]; then
        ip=$(hostname -I | cut -d ' ' -f 1)
        pwd=$(pwd | cut -d '/' -f 5-)
        path_modificado=$(uriencode "$my_mpd")
        base_uri="http://${ip}/${pwd}/${path_modificado}"
        youtube-dl -f bestvideo+bestaudio "$base_uri"
    else
        # youtube-dl -f bestvideo+bestaudio $url_mpd
        youtube-dl $url_mpd
    fi
    
    for i in `ls -t *.mp4 *.mkv *.avi *.mpg`
    do
        mv "$i" "${manifest_title%.*}.mp4"
    done 2>/dev/null
    rm "$my_mpd"

}

function QuitarLimite()
{
    FILEID="${id}"
    # if grep -q "Permission denied" "$datosDescarga"; then
    if grep -q "Too many users have viewed or downloaded this file recently" "$datosDescarga"; then
        echo -e "\n"
        echo -e "\033[1;31mEnlace descargado demaciadas veces (Quota Exceeded)\033[0m"
        echo -e "\n"
        RD1=$(pwd)
        msg -ama "Generando nuevo enlace..."
        echo -e "\n"
        cd $RUTACOPYLIMITE && drive copy -id "$FILEID" ${NAMEBINDERCOPY};
        FILENAME=$(wget -q --show-progress -O - "https://drive.google.com/file/d/${FILEID}/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')
        drive pub ${NAMEBINDERCOPY}/"${FILENAME}"
        newlink=$(drive pub ${NAMEBINDERCOPY}/"${FILENAME}" | awk  -F "published on" '{print $2}')
        newlinkID=$(echo $newlink | awk -F "=" '{print $2}')
        FILEID=${newlinkID}
        cd $RD1
        echo "$newlinkID"
    fi
}

function quitarPermiso()
{
    RD1=$(pwd)
    miIde=${1}
    cd $RUTACOPYLIMITE && drive unpub -id "${miIde}" 2>/dev/null
    cd $RD1
}

function limite2()
{
    ruta=$(pwd)
    id=${1}
    msg -verm "SEGUNDO INTENTO"
    # cd /root/.Mydrive3 && drive copy -id ${id} peli;
    FILENAME=$(wget -q --show-progress -O - "https://drive.google.com/file/d/${id}/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')
    echo "nombre de la peli $FILENAME"
    # rclone move copi1:/${FILENAME} drive5:/Movies/ -P
    rclone copy ${MI_CUENTA_ILIMIADA}:/"Filecopy/${FILENAME}" ${RESPALDO_SEGUNDO}:/Movies/ -P
    link=$(rclone link ${RESPALDO_SEGUNDO}:/"Movies/${FILENAME}");
    link=$(echo $link | awk -F "=" '{print $2}')
    echo ${link};
    # rclone delete copi1:/
    # rclone cleanup copi1:/
    cd $ruta;
}


function GoogleDriveDescarga()
{
    # FILEID=$1
    # drive pull -id $FILEID
    # FILEID=$1
    # FILEID="$(echo $FILEID | sed -n 's#.*\https\:\/\/drive\.google\.com/file/d/\([^.]*\)\/view.*#\1#;p')";
    # FILEID="$(echo $FILEID | sed -n 's#.*\https\:\/\/drive\.google\.com/file/d/\([^.]*\)\/view.*#\1#;p')";
    # FILENAME="$(wget -q --show-progress -O - "https://drive.google.com/file/d/$FILEID/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Dysk\ Google</title>.*!\1!p')";
    # FILENAME="$(wget -q --show-progress -O - "https://drive.google.com/file/d/$FILEID/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')";
    # FILENAME1=$(echo "$FILENAME")
    # wget -q --show-progress --save-cookies /tmp/cookies.txt --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILEID" -O $FILENAME
    # # read -p "salirrrr"

    # FILENAME2=$(echo "$FILENAME" | awk '{print $1}')
    # echo $FILENAME2
    # read -p "nombre rriva"
    
    function ProgressBar(){
    chars="/-\|" 
    while :; do 
        for (( i=0; i<${#chars}; i++ )); do
        sleep 0.1
        printf " "; echo -en "${chars:$i:1}" "\r"
        done 
    done & trap 'kill $!' SIGTERM SIGKILL

    }


    function compro(){

        if grep -q "Quota exceeded" "$FILENAME2"; then
            rm "$FILENAME" && \
            echo -e "\033[1;31mEnlace descargado demaciadas veces (Quota Exceeded)\033[0m" && \
            echo "https://drive.google.com/file/d/$FILEID/view"
            echo -e "\033[1;33mFile \033[1;31m$FILENAME\033[0m \033[1;33mNO se puede DESCARGAR\033[0m" 
            echo -e "\n"
            echo -e "\n"
            msg -ama "GENERANDO NUEVO ENLACE..."

            RD1=$(pwd)
            cd $RUTACOPYLIMITE && drive copy -id "$FILEID" ${NAMEBINDERCOPY};
            drive pub ${NAMEBINDERCOPY}/"${FILENAME}"
            newlink=$(drive pub ${NAMEBINDERCOPY}/"${FILENAME}" | awk  -F "published on" '{print $2}')
            newlinkID=$(echo $newlink | awk -F "=" '{print $2}')
            FILEID=${newlinkID}
            cd $RD1
            ProgressBar
            msg -ama "Por favor, espere..."
            sleep 7s
            kill $!
            FILENAME=$(wget -q --show-progress -O - "https://drive.google.com/file/d/$FILEID/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')
            FILENAME1=$(echo "$FILENAME")
            wget -q --show-progress --save-cookies /tmp/cookies.txt --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILEID" -O $FILENAME

            FILENAME2=$(echo "$FILENAME" | awk '{print $1}')

            if grep -q "Quota exceeded" "$FILENAME2"; then
                rm "$FILENAME" && \
                echo -e "\033[1;31mEnlace descargado demaciadas veces (Quota Exceeded)\033[0m" && \
                echo "https://drive.google.com/file/d/$FILEID/view"
                echo -e "\033[1;33mFile \033[1;31m$FILENAME\033[0m \033[1;33mNO se puede DESCARGAR\033[0m" 
            else
                echo -e "\033[1;33mFile \033[1;36m$FILENAME1\033[0m \033[1;33mONLINE\033[0m"
                sleep 2
                rm "$FILENAME" 2>/dev/null
                rm "$FILENAME2" 2>/dev/null
                # ONLINE=$(echo "$FILENAME")
                # ENLACESVIVOS[$i]=$(echo "$FILEID")
            fi

        else

            echo -e "\033[1;33mFile \033[1;36m$FILENAME1\033[0m \033[1;33mONLINE\033[0m"
            rm "$FILENAME2" && \
            ONLINE=$(echo "$FILENAME")
            ENLACESVIVOS=$(echo "$FILEID")
        fi
    }



    function newEnlace()
    {

        msg -ama "GENERANDO NUEVO ENLACE..."

        RD1=$(pwd)
        cd $RUTACOPYLIMITE && drive copy -id "$FILEID" ${NAMEBINDERCOPY}; 
        drive pub ${NAMEBINDERCOPY}/"$FILENAME"
        newlink=$(drive pub ${NAMEBINDERCOPY}/"$FILENAME" | awk  -F "published on" '{print $2}')
        newlinkID=$(echo $newlink | awk -F "=" '{print $2}')
        FILEID=${newlinkID}
        cd $RD1
        ProgressBar
        msg -ama "Por favor, espere..."
        sleep 5s
        kill $!

    }


    function googleDescarga () 
    {
        CONFIRM_CODE=$(wget -q --show-progress --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILEID" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
        wget -q --show-progress --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$CONFIRM_CODE&id=$FILEID" -c -O "$FILENAME" && rm -rf /tmp/cookies.txt;
        error=$?
        echo $error
        NAMEFILEE=$(msg -verd "$FILENAME")
        echo "file $NAMEFILEE DESCARGADO"
        ls -alh
        echo -e "\n"
        # read -p "paradooo"


    }



    function CompVideo()
    {
        extv="$1"; ext=${extv##*.}
        case $ext in
            mkv ) EXTVIDEO="mkv";;
            mp4 ) EXTVIDEO="mp4";;
            avi ) EXTVIDEO="avi";;
            mpg ) EXTVIDEO="mpg";;
            *) msg -azu "NO ES UN VIDEO";;
        esac

        if [[ $ext == $EXTVIDEO && -f "$FILENAME" ]]; then

            ORIFILENAME=${extv}
            mv -- "${extv}" "${extv//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}" 2>/dev/null;
            extv=${extv//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}
            vi=$(ffprobe "$extv" 2>&1 | grep -i "stream" | wc -l)
            if [[ $vi -le 1 ]]; then
                until [[ $vi -ge 2 ]]; do
                    msg -red "ARCHIVO $FILENAME DAÑADO"
                    msg -ama "REINTANTANDO DESCARGA..."
                    sleep 8
                    rm -rf "$FILENAME"
                    googleDescarga
                    mv -- "${ORIFILENAME}" "${ORIFILENAME//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}" 2>/dev/null;
                    extv=${ORIFILENAME//['][!”#$%&’()*+,/ :;<=>?@\^_`{\|}~-']/_}
                    vi=$(ffprobe "$extv" 2>&1 | grep -i "stream" | wc -l)
                done

            else
                msg -ama "$ORIFILENAME SALUDABLE"
            fi
            mv -- "${extv}" "$ORIFILENAME" 2>/dev/null

        elif [[ $ext = "rar" ]]; then
                unrar t -p$PASSRAR $1
                err=$?
                echo $err
                numerr='[1-2]'
                if [[ $err = $numerr ]]; then
                    while :; do
                        msg -ama "RAR DAÑADO. REITENTANDO..."
                        rm -rf "$FILENAME"
                        googleDescarga
                        unrar t -p$PASSRAR "$FILENAME"
                        err=$?
                        [[ $err != $numerr ]] && break;
                        # if [[ $err != $numerr ]]; then
                        #     break
                        # fi
                    done
                fi
        fi

    }



    function drivego()
    {
        msg -pur "DESCARGANDO CARPETA"
        compro
        s=$(pwd)
        s1=$(pwd | cut -d "/" -f7)
        cd /root/.gd1/$s1 && echo | drive pull -id $FILEID
        
        err=$?
        if [[ $err != 0 ]]; then
            compro; googleDescarga; CompVideo "$FILENAME"
        fi
        find . -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.avi" -o -name "*.mpg" \) -exec mv {} $s 2>/dev/null \;
        cd $s
        # mv -- * "$s" && cd $s
    }
















    compro
    googleDescarga
    inte=1

    until [[ -s $FILENAME ]]; do

        googleDescarga
        echo "reitentando..."
        ls -alh "$FILENAME"
        sleep 2;

    done
    
    
    # echo "$FILENAME"

    sta=$(stat -c %s "$FILENAME")
    if [[ -d "$FILENAME" || $sta -eq 0 ]]; then
        drivego
        unset FILENAME
    fi



    if [[ ${FILENAME##*.} != "srt" && -f "$FILENAME" ]]; then
        pesodelarchi=$(stat -c %s "$FILENAME" | wc -L)
        # echo "ES UN FICHEROOOOO"
    fi

    e=1
    if [[ $FILENAME && -f "$FILENAME" ]]; then

    until [[ $pesodelarchi -ge 5 ]]; do
        sleep 5
        rm -rf "$FILENAME"
        googleDescarga
        msg -ama "Reintentando..."
        pesodelarchi=$(stat -c %s "$FILENAME" | wc -L)
        if [[ $e -eq 10 ]]; then
            break
        fi
        if [[ $e -eq 3 ]]; then
            newEnlace; googleDescarga
            # drivego
            pesodelarchi=$(stat -c %s "$FILENAME" | wc -L)
        fi
        let e=$e+1
    done
    fi


    if [[ $error = 0 ]]; then
        CompVideo "$FILENAME"
    fi

    RD1=$(pwd)
    cd $RUTACOPYLIMITE && drive unpub -id "${FILEID}" 2>/dev/null
    cd $RD1
}

if [[ $host == "drive.google.com" || $host == "docs.drive.com" ]]; then
    id=$(php /var/www/html/panel/inc/comp/parse_url.php "${1}")
    # GoogleDriveDescarga $id
    gdown --id $id 2>&1 | tee $datosDescarga
    QuitarLimite      #https://drive.google.com/open?id=$newlinkID
    # [[ $newlinkID ]] && msg -verd "Nuevo enlace generado: " && msg -pur "https://drive.google.com/open?id=$newlinkID"

    if [[ $newlinkID ]]; then
        msg -verd "Nuevo enlace generado: " && msg -pur "https://drive.google.com/open?id=$newlinkID" && rm $datosDescarga
        gdown --id $newlinkID 2>&1 | tee $datosDescarga

        if grep -q "Too many users have viewed or downloaded this file recently" "$datosDescarga"; then
            msg -red "ENLACE CON LIMTE!!... NO SE PUEDE DESCARGAR"
            limite2 ${newlinkID};
            gdown --id ${link} 2>&1 | tee $datosDescarga
        fi

        quitarPermiso "$newlinkID"
    fi

elif [[ $host == "www.mediafire.com" ]]; then
    deUniversal $1
elif [[ $host == "mega.nz" || $host == "mega.co.nz" ]]; then
    # megadl $1
    mega-get "$1"
elif [[ $host == "uptobox.com" ]]; then
    down_uptobox.sh $1
elif [[ $host == "uptostream.com" ]]; then
    down_uptobox.sh $1
elif [[ $host == "www.viki.com" || $host == "viki.com" ]]; then
    . /usr/local/bin/function.sh
    viki_download $1
    # editar_sub "Viki" "cine24h" 
elif [[ $host == "www.fembed.com" || $host == "fembed.com"  ]]; then
    echo "DESCARGANDO FEMBED.."
    . /usr/local/bin/function2.sh
    # python3.7 /usr/local/bin/fembed_download_720.py -L "${1}" -c "720p"
    lf=$(descargar_720_fembed_final "${1}")
    echo "$lf"
    sleep 3
    if [ -n "${lf}" ]; then
        echo "$lf"
        aria2c -x16 -s16 "${lf}"
    else
        msg -ama "NO SE ENCONTRO EL ENLACE"
    fi
    
    
      
elif [[ $proto == "https://" || $proto == "http://" ]]; then
    aria2c -x16 -s16 "${1}"    
else

    if [[ "$2" == "de3" ]]; then
        . /usr/local/bin/function2.sh
        descargarFilesFolderIDCarpeta "${1}" "gearvpn"
    else
        . /usr/local/bin/function.sh
        descargarFilesFolderID "${1}"
    fi
fi


MiPeli=$(ls *.mp4 *.mkv *.avi *.mpg 2>/dev/null)
pesodelarchi=$(ls -alh "$MiPeli"| awk '{print $5}' | grep "G")
pesodelarchi2=$(ls -alh "$MiPeli"| awk '{print $5}' | grep "M")

if [ "$pesodelarchi" -o "$pesodelarchi2" ]; then
    msg -azu "DESCARGA CORRECTA!"
else
errorRuta=$(pwd | cut -d"/" -f7)
    echo "$1" >> ../.${errorRuta}_errorDownload.txt
fi

