#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'anime-downloader==5.0.7','console_scripts','anime'
__requires__ = 'anime-downloader==5.0.7'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('anime-downloader==5.0.7', 'console_scripts', 'anime')()
    )
