#!/bin/bash
PELI_O_SERIE=$(echo $0 | cut -d"/" -f5)

function elemento2()
{   
    RUTA_T=$(pwd)
    opcion=7
    FILEIDD=$(php /var/www/html/panel/inc/comp/parse_url.php "${FARRAY[0]}")
    [[ ! $ID_DB_PELI ]] && activarPlantilla=true
    [[ ${EXTRAER_GDRIVE} == "1080" ]] && CALIDA1="(1080)" && gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ${EXTRAER_GDRIVE} == "720" ]] && CALIDA1="(720)" && yt-dl2.sh "${FARRAY[0]}" #gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ${EXTRAER_GDRIVE} == "480" ]] && CALIDA1="(480)" && gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ${EXTRAER_GDRIVE} == "360" ]] && CALIDA1="(360)" && gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"
    [[ ! ${EXTRAER_GDRIVE} ]] && drived
    SAVEIFS=$IFS; 
    IFS=$(echo -en "\n\b")
    TArchivo;
    descompri; 
    _quitar_audio
    EscogerAudio;
    PegarSubtitulos;
    [[ -z "${EXTRASUB}" && -n "${MARCA_AGUA}" ]] && pegarLogo
    aguaMarca;
    [[ ! $ID_DB_PELI ]] && addBd;
    [[ -n "${iframe}" ]] && echo "${iframe}" > ".iframe"
    renom; 
    ConvertirPeli; 
    for i in "${SERVIDORES[@]}"; do
        case $i in
            1080) subida_o_s_s_1080 $OMITIR; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            720) subida_o_s_s_720; IFS=$SAVEIFS; sudmenu; 2>/dev/null
            ;;
            "720p") subida_o_s_s_720p; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            "CAM") subida_cam; IFS=$SAVEIFS; sudmenu; 2>/dev/null
            ;;
            "HD") subida_cam; IFS=$SAVEIFS; sudmenu; 2>/dev/null;
            ;;
            "hqq.to"|"jetload"|"uptobox"|"gounlimited"|"mega"|"gdfree"|"gdvip"|"mystream"|"fembed"|"backup") SERVIDOR_A_BUSCAR="${i}"; 
            ServidorAll "$MiPeli" " " "$SERVIDOR_A_BUSCAR" "$SERVIDOR_A_BUSCAR" "$ID_DB_PELI"
            ;;
            *) echo "default 2"
            ;;
        esac
    done
    # IFS=$SAVEIFS; 
    # sudmenu 2>/dev/null
    # && rm "$MiPeli"
    
    cd ${RUTA_T}; [[ -z "$borrar" ]] && rm -rf ${RUTA_T}/*
    
    
}

function elemeto1()
{
    if [[ "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "720" || "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "1080" || "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "480" || "${FARRAY[0]}" =~ "drive.google.com" && ${EXTRAER_GDRIVE} == "360" ]];then
        FILEIDD=$(php /var/www/html/panel/inc/comp/parse_url.php "${FARRAY[0]}")
        opcion=7
        activarPlantilla=true #Activar la creacion de la plantilla en el panel web
        case "$CALIDA1" in
            1080) CALIDA1="(1080)"; 
            gooledd720 ${FILEIDD} "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_1080; IFS=$SAVEIFS; sudmenu 2>/dev/null 
            ;;
            720) CALIDA1="(720)";
            gooledd720 "${FILEIDD}" "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            480) CALIDA1="(480)";
            gooledd720 "${FILEIDD}" "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            360) CALIDA1="(360)";
            gooledd720 "${FILEIDD}" "${EXTRAER_GDRIVE}p"; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            *) echo default; exit
            ;;
        esac
    fi
    
}

function elemeto2_720p()
{
    # PARAMETRO DEFINIDO PARA PODER DESCARGAR
        opcion=7
        activarPlantilla=true #Activar la creacion de la plantilla en el panel web
        case "$CALIDA1" in
            1080) CALIDA1="(1080)"; 
                drived; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_1080; IFS=$SAVEIFS; sudmenu 2>/dev/null 
            ;;
            720) CALIDA1="(720)";
                drived; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            "720p") CALIDA1="(720)";
                drived; TArchivo; descompri; aguaMarca; EscogerAudio; addBd; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; subida_o_s_s_720p; IFS=$SAVEIFS; sudmenu 2>/dev/null
            ;;
            "hqq.to"|"jetload"|"uptobox"|"gounlimited"|"mystream"|"fembed") 
            SERVIDOR_A_BUSCAR=${CALIDA1}; drived; TArchivo; descompri; aguaMarca; EscogerAudio; PegarSubtitulos; SAVEIFS=$IFS; renom; ConvertirPeli; IFS=$SAVEIFS; ServidorAll "$MiPeli" " " "$SERVIDOR_A_BUSCAR" "$SERVIDOR_A_BUSCAR" "$ID_DB_PELI"
            ;;
            *) echo default; exit
            ;;
        esac
}

function Respaldo()
{
    local enlace

    echo "este es el enlace que se enviara: ${FARRAY[0]}"
    echo 
    # enlace=$(respaldoBackup "${FARRAY[0]}")
    respaldoBackup "${FARRAY[0]}" enlace
    echo "lo qque se esperesa: ${enlace}"
    agregarRespaldoBd "${ID_UNICO}" "${enlace}" "admin"
}

function obtenerLinkCalidad()
{
    local URL=$1
    local CALIDAD=$2

    FILEIDD=$(php /var/www/html/panel/inc/comp/parse_url.php "${URL}")
    gooledd720 ${FILEIDD} "${CALIDAD}"

    FILENAME=$(wget -q --show-progress -O - "https://drive.google.com/file/d/${FILEIDD}/view" | sed -n -e 's!.*<title>\(.*\)\ \-\ Google\ Drive</title>.*!\1!p')
    rclone copy "${FILENAME}" drive7:/obt_calidades -P
    rclone link drive7:/obt_calidades/"${FILENAME}"
}
function getApiMaxpelis () {
    CAN_ID="${1}"
    for ((iCAN_ID=${CAN_ID};iCAN_ID<4000;iCAN_ID++)); do
        data=$(curl "https://maxpelis.tk/rest-api/v130/moviesCuevana/?API-KEY=b61gaoi3iq2sdzrs5j2n1sbv&movie_id=${iCAN_ID}" | jq -r '.')
        echo "$iCAN_ID"
        status=$(echo "${data}" | jq -r '.status')
        
        if [[ "$status" == 'success' ]];then
            echo "${data}" | jq -r '.data.maxpelis_id' >> "../.max.log"
            title=$(echo "${data}" | jq -r '.data.title')
            quality=$(echo "${data}" | jq -r '.data.quality')
            tmdb=$(echo "${data}" | jq -r '.data.tmdb')

            latino=$(echo "${data}" | jq -r '.data.latino')
            castellano=$(echo "${data}" | jq -r '.data.castellano')
            subtitulado=$(echo "${data}" | jq -r '.data.subtitulado')

            SERVIDORES[0]="HD"

            if [[ -n "${title}" ]]; then
                nameori=${title^^}
                FILEE=${title^^}
                NAMESERI=${title^^}
            fi
            
            if [[ "${quality}" == "HD" ]];then
                CALIDA1="HD"
            elif [[ "${quality}" == "CAM" ]];then
                CALIDA1="CAM"
            else
                CALIDA1="DVD"
            fi

            [[ "${tmdb}" != "null" ]] && IDPELICULA="${tmdb}"


            if [[ -n "${latino}" && ! "${latino}" =~ "/sc/index.php?h=" && ! "${latino}" =~ "/fembed/?h=" && ! "${latino}" =~ "/player.php?h=" ]];then

                IDIOMA1="LAT"
                IDIOMA3="LAT"
                ifram=$(echo "$latino" | cut -d"=" -f2);
                iframe="https://formatearwindows.net/embed.html#${ifram}"
                arrIframe+=("${iframe}")

                FARRAY[$n]="https:${latino}"
                link[$n]="https:${latino}"

                echo "#REQUEST -> NAME: ${nameori}"
                echo "#REQUEST -> IDIOMA: LATINO"
                echo "#REQUEST -> CALIDAD: ${CALIDA1}"
                echo "#REQUEST -> TMDB: ${IDPELICULA}"
                echo "#REQUEST -> IFRAME: ${iframe}"
                elemento2
            fi

            if [[ -n "${castellano}" && ! "${castellano}" =~ "/sc/index.php?h=" && ! "${castellano}" =~ "/fembed/?h=" && ! "${castellano}" =~ "/player.php?h=" ]];then

                IDIOMA1="ESP"
                IDIOMA3="ESP"
                ifram=$(echo "$castellano" | cut -d"=" -f2);
                iframe="https://formatearwindows.net/embed.html#${ifram}"
                arrIframe+=("${iframe}")

                FARRAY[$n]="https:${castellano}"
                link[$n]="https:${castellano}"

                echo "#REQUEST -> NAME: ${nameori}"
                echo "#REQUEST -> IDIOMA: ESP"
                echo "#REQUEST -> CALIDAD: ${CALIDA1}"
                echo "#REQUEST -> TMDB: ${IDPELICULA}"
                echo "#REQUEST -> IFRAME: ${iframe}"
                elemento2
            fi

            if [[ -n "${subtitulado}" && ! "${subtitulado}" =~ "/sc/index.php?h=" && ! "${subtitulado}" =~ "/fembed/?h=" && ! "${subtitulado}" =~ "/player.php?h=" ]];then

                IDIOMA1="SUB"
                IDIOMA3="SUB"
                ifram=$(echo "$subtitulado" | cut -d"=" -f2);
                iframe="https://formatearwindows.net/embed.html#${ifram}"
                arrIframe+=("${iframe}")

                FARRAY[$n]="https:${subtitulado}"
                link[$n]="https:${subtitulado}"

                echo "#REQUEST -> NAME: ${nameori}"
                echo "#REQUEST -> IDIOMA: SUB"
                echo "#REQUEST -> CALIDAD: ${CALIDA1}"
                echo "#REQUEST -> TMDB: ${IDPELICULA}"
                echo "#REQUEST -> IFRAME: ${iframe}"
                elemento2
            fi
        fi
    done
}

# echo "OPTIND inicia en $OPTIND"
v=0; n=0 
arrIframe=()
puesto=$(pwd | cut -d "/" -f7)
fifoCue="/tmp/fifo${puesto}cue"
[[ -e $fifoCue ]] && rm $fifoCue
while getopts "c:t:n:e:i:s:a:p:o:m:L:F:C:I:K:V:T:R:E:B:W:A:" optname
  do
    case "$optname" in
        "A")
            APIPERMISO=$OPTARG;
            ;;
        "W")
            ifram=$(echo "$OPTARG" | cut -d"=" -f2);
            iframe="https://formatearwindows.net/embed.html#${ifram}"
            echo "$iframe" >> "${fifoCue}"
            # arrIframe+=("${iframe}")
            ;;
        "m")
            MARCA_AGUA=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "a")
            ID_DB_PELI=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "V")
            URL_VIKI=$OPTARG;
            # URL PARA VIKI
            ;;
        "T")
            NT=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "R")
            EPI=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "E")
            temp=$OPTARG;
            # CANTIDAD DE ENLACES
            ;;
        "B")
            borrar=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "o")
            OMITIR=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "s")
            if [[ $OPTARG == 'sub-rar' ]];then
                SUBRAR=true
            elif [[ $OPTARG == 'sub-mkv' ]]; then
                EXTRASUB=true
            else
                LSUB=$OPTARG
            fi
            
            
        # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
        ;;
        "p")
            PSW6=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "c")
            CALIDA1="($OPTARG)";
            

            # [[ $CALIDA1 == "netu" ]] && CALIDA1="hqq.tv";
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "K")
            SERVIDORES[$v]=$OPTARG;
            SERVIDOR_BUSCAR=${OPTARG^^}
            [[ $OPTARG == "1080" ]] && opcion1=3
            [[ $OPTARG == "720" ]] && opcion1=4
            [[ "${SERVIDOR_BUSCAR}" == "MEGA" ]] && opcion1=5
            ((v++))
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "C")
            EXTRAER_GDRIVE=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "I")
            ID_UNICO=${OPTARG}; ID_DB_PELI=$OPTARG;
            # echo "Se ha especificado la opción $optname y su valor es $CALIDA1"
            ;;
        "e")
            FARRAY[$n]="${OPTARG}"
            link[$n]="${OPTARG}"
            ((n++))
            # echo "La opción $optname tiene el valor ${FARRAY[0]}"
            ;;
        "n")
            nameori=${OPTARG^^}
            FILEE=${OPTARG^^}
            NAMESERI=${OPTARG^^}
            # echo "La opción $optname tiene el valor $nameori"
            ;;
        "t")
            IDPELICULA=$OPTARG
            IDSERIE=$OPTARG
            # echo "La opción $optname tiene el valor $IDPELICULA"
            ;;
        "i")
            IDIOMA1=${OPTARG^^}
            IDIOMA3=${OPTARG^^};
            [[ $IDIOMA1 == "INGLES" ]] && IDIOMA1="SUB" && IDIOMA3="SUB";
            [[ $IDIOMA1 == "LATINO" ]] && IDIOMA1="LAT" && IDIOMA3="LAT";
            [[ $IDIOMA1 == "CASTELLANO" ]] && IDIOMA1="ESP" && IDIOMA3="ESP";
            
            # echo "La opción $optname tiene el valor $IDIOMA1"
            ;;
        # "s")
        #     if [[ $OPTARG == "mkv" ]];then
        #         EXTRASUB=true
        #     else
        #         LSUB="${OPTARG}"
        #         CSUB=1
        #     fi
        #     # echo "La opción $optname tiene el valor $IDIOMA1"
        #     ;;
        "L")
            ACTIVARAUDIO=$OPTARG
            ;;
        "F")
            ELIMINARSUB=$OPTARG
        ;;
        "?")
            echo "Opción desconocida $OPTARG"
            ;;
        ":")
            echo "Sin valor de argumentos para la opción $OPTARG"
            ;;
        *)
        # Should not occur
            echo "Error desconocido mientras se procesaban las opciones"
            ;;
        esac
        # echo "OPTIND ahora es $OPTIND"
        # echo "----VUELTA # $v -------"
done

#imbocar api maxpeli.tk
[[ -n "${APIPERMISO}" ]] && getApiMaxpelis "${APIPERMISO}" && exit

if [[ "$PELI_O_SERIE" == 'se3' ]]; then

    #cantidad de temporadas
    cant=1
    if [[ $URL_VIKI ]]; then
        comprobarEnlaceViki "$URL_VIKI" $temp
    else
        temp="${#link[@]}"
        echo "temp $temp"
        echo "link: ${link[@]}"
        echo "${ACTIVARAUDIO}"
        echo "${ELIMINARSUB}"
        _quitar_audio
    fi
    drive3 1

else
    case ${SERVIDORES[0]} in
        "hqq.to"|"jetload"|"uptobox"|"gounlimited"|"mega"|"gdfree"|"gdvip"|"fembed"|1080|720|720p|"CAM"|"HD") elemento2
        ;;
        "backup") msg -ama "creando BACKUP..."; BackupMega "${FARRAY[0]}" $ID_DB_PELI 
        ;;
        "obt_1080") CALIDAD="1080p"; obtenerLinkCalidad ${FARRAY[0]} $CALIDAD
        ;;
        *) echo "Servidor no especificado: default 1"
        ;;
    esac

fi

exit


